### ISSUE TITLE
list index out of range error in getdatum Funktion

### ISSUE THREAD

**Issue by t3g** [prof-membrane/plugin.video.brmediathek#3]
Hallo membrane,

erst einmal Respekt, deine Addons sind super praktisch!
Seit kurzem funktioniert die BR Mediathek nicht mehr, wenn die Videos nach Buchstaben sortiert werden. Hier ein Error Log:
[BR_Error.txt](https://github.com/prof-membrane/plugin.video.brmediathek/files/1412575/BR_Error.txt)

Vermutlich wurde die Seite umgebaut und das parsing funktioniert nicht mehr?
Ich benutze das Addon in Kodi Krypton unter Libre Elec - ggf. ist es noch V1.0 und nicht V1.1.0 - wenn ja, dann war diese issue umsonst ;).

**Comment by t3g** [comment]
Fehler von meiner Seite - das Addon, das bei mir im Repository angeboten wird, ist ein fork von membrane :/

**Comment by prof-membrane** [comment]
Im Moment geht in meiner Version nur die Auflistung AZ. Die Mediathek wurde vor kurzer Zeit komplett umgestellt. Ich bin überrascht, dass dies schon passierte. Es fehlt eine Vielzahl an Features, die ich vermisse. Ohne Dokumentation wird es noch ein wenig dauern, bis ich annähernd den alten Zustand wiederherstellen kann. Das neue Interface ist sehr komplex.

**Comment by prof-membrane** [comment]
Die Mediathek wurde vor kurzer Zeit komplett umgestellt. Ich bin überrascht, dass dies schon passierte. Es fehlt eine Vielzahl an Features, die ich vermisse. Ohne Dokumentation wird es noch ein wenig dauern, bis ich annähernd den alten Zustand wiederherstellen kann. Das neue Interface ist sehr komplex.

Im Moment greift das Add-on noch teilweise auf das alte Interface zu. Es ist eine nur Frage der Zeit, wie lange das noch gut geht. Die Untertitel musste ich schon entfernen. Ich kann mich frühstens am Wochenende darum kümmern.

**Comment by t3g** [comment]
Leider ist auch mit der aktuellen Version dieses Repos (1.1.0 - auf 1.1.1 kann ich irgendwie nicht updaten) die BR Mediathek nicht mehr funktionsfähig.
Kann ich irgendwie unterstützen? Ich habe mir schon mal den Parser angesehen - da steckt ziemlich viel im Detail drin... Wenn sich die Seite ändert ist mir jetzt klar, wieso nichts mehr geht...

**Comment by prof-membrane** [comment]
Der neue Parser wird viel abgefahrener. Ich habe die Bibliothek dahinter auf das neue API umgeschrieben. In meinem Repo befindet sich eine Vorabversion.
