### ISSUE TITLE
Fehler bei BR Mediathek: Error Type: <type 'exceptions.IndexError'>

### ISSUE THREAD

**Issue by kodi-beginner** [prof-membrane/plugin.video.brmediathek#4]
Hallo zusammen,

bei der Nutzung der Video-Addons BR Mediathek (von membrane - 1.0.0.) oder des Bayerischen Fernsehens (von LORE - 0.7.8) bekomme ich beim Aufruf von Sendungen (speziell geht es um die Serie Dahoam is Dahoam, die 1. Staffel und die aktuellen Sendungen) immer die folgenden Fehlermeldungen:
- BR Mediathek Fehler
- Wiedergabe nicht möglich. Mindestens eine Datei konnte nicht abgespielt werden. Für mehr Details Logdatei einsehen.

Auch bei anderen Sendungen in der BR Mediathek erhalte ich den gleichen Fehler.

Ich betreibe Kodi 17.6, LibreElec 8.2.2 auf einem Raspberry Pi 3 und 32 GB SD-Karte.

Auszug aus dem Log: Log im Anhang

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.brmediathek/default.py", line 4, in <module>
libbr.list()
File "/storage/.kodi/addons/script.module.libbr/lib/libbr.py", line 108, in list
libMediathek.play(libBrPlay())
File "/storage/.kodi/addons/script.module.libmediathek3/lib/libmediathek3.py", line 89, in play
subFile = ttml2Srt(subtitle['url'])
File "/storage/.kodi/addons/script.module.libmediathek3/lib/libmediathek3ttml2srt.py", line 14, in ttml2Srt
return _newSubtitle(url)
File "/storage/.kodi/addons/script.module.libmediathek3/lib/libmediathek3ttml2srt.py", line 34, in _newSubtitle
d = _stylesSetup(re.compile('<styling>(.+?)</styling>', re.DOTALL).findall(content)[0])
IndexError: list index out of range
-->End of Python script error report<--

Bei den Kodinerd habe ich den Rat bekommen hier ein Issue zu eröffnen und habe dort noch folgende Infos bekommen (Auszug):

"...der Fehler: "IndexError: list index out of range" besagt, dass die vom Script gesuchte Stelle auf der Webseite NICHT gefunden wurde.
Habe gerade auf Windows mit KODI 17.6 getestet, die meisten Videos vom "BR" [plugin.video.brmediathek v.1.1.0] (Autor vorm. membrane) lassen sich NICHT abspielen, da das "https:" am Anfang der Links fehlt, auch wird häufig ein Fehler, wie z.B. UnboundLocalError: local variable 'videoUrl' referenced before assignment oder NameError: global name '_parseMain' is not defined beim öffnen der Ordner angezeigt."

Link: 
https://www.kodinerds.net/index.php/Thread/59689-Fehler-bei-BR-Mediathek-Error-Type-type-exceptions-IndexError/

Vielen Dank für die Unterstützung.

Gruß
kodi-beginner 
[Kodi-Log-BR-Mediathek.txt](https://github.com/prof-membrane/plugin.video.brmediathek/files/1601335/Kodi-Log-BR-Mediathek.txt)

**Comment by prof-membrane** [comment]
Ich habe die entsprechende Bibliothek für die neue Mediathek umgeschrieben. In meinem Repo gibt es die neue Version.
